name: Unit Tests

on: ["push", "pull_request"]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Setup environment
        uses: alessiofrittoli/github-actions/.github/actions/setup-pnpm-node@feature/add-Setup-pnpm-and-Node.js-composite-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          additional_pnpm_configs: "config=value;config2=value;"

      - name: Linting
        run: pnpm lint

      - name: Type checking
        run: pnpm tsc

      - name: Run unit tests
        run: pnpm test:coverage:ci

      - name: Report to Coveralls
        uses: coverallsapp/github-action@v2
        if: success()
        continue-on-error: true
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          file: coverage/lcov.info
          allow-empty: true
